### ISSUE TITLE
Agregar sección de noticias en la portada del sitio web

### ISSUE THREAD

**Issue by cmaureir** [pythoncanarias/pycones23#12]
Como primera noticia, podemos generar un mensaje simple que sea la "primera noticia" del sitio web, algo como:

> ¡Lanzamiento del sitio web! - 2023.03.XX
> 
> Ya hemos publicado la primera versión del sitio web de la conferencia con algunas secciones importantes para las personas interesadas en participar.
> Estaremos publicando más actualizaciones en las siguientes semanas

**Comment by jata84** [comment]
Lo he puesto justo debajo del título y encima del cronograma (milestone)
![image](https://user-images.githubusercontent.com/7282535/228350989-b4cd5601-36b6-4e31-8b42-c1df17c015d4.png)

A los títulos de las secciones (h1) de "noticias" y "cronograma del evento" me gustaría darle una vuelta
