### ISSUE TITLE
Agregar tabla con addons y niveles de patrocinios

### ISSUE THREAD

**Issue by jata84** [pythoncanarias/pycones23#14]
Agregar tabla con addons y niveles de patrocinios, confirmar información con patrocinios cuando esté completo información en discord

![image](https://user-images.githubusercontent.com/7282535/228147734-55bd0743-b54e-4e16-870c-8616561f653c.png)

**Comment by sosahcarlos** [comment]
Acabo de subirlo. En escritorio se ve bien pero en móvil las tablas no son muy funcionales.
Habría que decidir si vale la pena hacer algo especifico para móvil o directamente ocultar la tabla y que la persona acceda a esa información descargando el dosier.

**Comment by cmaureir** [comment]
quizás quitar las imagenes así quizás cada columna tendría un width mucho más pequeño y se podría ver bien? podemos jugar también con reducir el tamaño del texto de la tabla para  mobile

**Comment by sosahcarlos** [comment]
Puede funcionar, lo pruebo 👍

**Comment by sosahcarlos** [comment]
Subido, con lo que comentaste y un scroll horizontal para las pantallas mas pequeñas parece suficiente 🙌
