### ISSUE TITLE
Resaltar la sección activa

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/pycones23#16]
¿Sería posible resaltar la sección activa en cada momento?

![Captura de pantalla 2023-03-26 a las 19 46 10](https://user-images.githubusercontent.com/1591599/227797290-8d576469-3466-4961-a144-de2b21e66f97.png)

**Comment by jata84** [comment]
Buen aporte! lo metemos sin problemas!

**Comment by sosahcarlos** [comment]
![CleanShot 2023-04-01 at 16 33 56@2x](https://user-images.githubusercontent.com/4333825/229298822-d5fccb72-30e0-44ce-b89e-cc5539b8158e.png)

**Comment by sdelquin** [comment]
Estupendo
