### ISSUE TITLE
Magnificar fotos

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/pycones23#17]
¿Sería posible magnificar mucho más las fotos cuando se pase por encima de ellas?
Lo digo con la idea de que se puedan ver mejor...

![Captura de pantalla 2023-03-26 a las 19 47 59](https://user-images.githubusercontent.com/1591599/227797354-4242e7c2-5bc5-49e4-b844-be8d6dea2e79.png)

**Comment by jata84** [comment]
esta mas o menos lo tengo, pero tengo problemas con el responsive y prefería no subirlo roto
![image](https://user-images.githubusercontent.com/7282535/227797449-fbb0db3b-6f86-4108-b092-8490afe5140d.png)
Conforme encuentre la solución lo meto!!

**Comment by sdelquin** [comment]
Estupendo! Yo incluso le daría más tamaño...

**Comment by sosahcarlos** [comment]
Yo puedo echarle un ojo al responsive a ver si encuentro alguna solución

**Comment by jata84** [comment]
![image](https://user-images.githubusercontent.com/7282535/228032436-988d3085-5baf-4dc3-a503-e2558d1118ca.png)

El responsive se ha quedado medio bien, ahora tengo otro problema con la superposición

![image](https://user-images.githubusercontent.com/7282535/228032687-ddcc5d35-9693-4c25-abfb-bb71d119a0f8.png)

**Comment by cmaureir** [comment]
IMVHO @jata84 yo lo veo hasta como un feature jaja no le echaría mucho tiempo

**Comment by sosahcarlos** [comment]
"Parcheado" lo de la superposición
