### ISSUE TITLE
Resaltar iconos de redes sociales

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/pycones23#18]
¿Se podrían resaltar los iconos de redes sociales cuando se pase por encima?

![Captura de pantalla 2023-03-26 a las 19 51 09](https://user-images.githubusercontent.com/1591599/227797559-cd28676a-69d8-4ecb-bdc0-f4e6ff5e30a3.png)

**Comment by jata84** [comment]
![image](https://user-images.githubusercontent.com/7282535/228032253-64e69f50-ac2f-4471-ae91-10fb0d1bbd1d.png)
He cogido de la paleta de colores el que creo que encaja mejor con el naranja

**Comment by sdelquin** [comment]
Y en el mismo violeta que está encima? Me da que contrasta más? 🤔

**Comment by jata84** [comment]
![image](https://user-images.githubusercontent.com/7282535/228134345-bec89cd2-59a9-4555-885b-b1f490e0c701.png)
![image](https://user-images.githubusercontent.com/7282535/228134807-fe5717e6-2068-47f4-9740-912be68cb748.png)
![image](https://user-images.githubusercontent.com/7282535/228135195-eeb78ebe-8b91-4eb2-a838-5c759ba1d1dc.png)

Te pongo las pruebas que he hecho, no tengo opinión clara

**Comment by cmaureir** [comment]
pues quizás lo dejamos así y cerramos el issue ¿les parece?
