### ISSUE TITLE
Crear seccion de FAQs

### ISSUE THREAD

**Issue by jata84** [pythoncanarias/pycones23#40]
### Background 

Se propone crear una sección de FAQs para las preguntas frecuentes y para poder remitir a ellas cuando las preguntas sean recurrentes

**Comment by cmaureir** [comment]
Como referencia, algunas cosas que se mencionan acá podrían ser preguntas y respuestas
* https://us.pycon.org/2023/onsite/onsite-information/
* https://us.pycon.org/2023/onsite/meal-ingredients/
