### ISSUE TITLE
¿Desaparecieron los enlaces a redes sociales?

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/pycones23#62]
Estaban en la esquina inferior derecha

**Comment by cmaureir** [comment]
![Screenshot 2023-05-30 at 21-37-14 PyConEs Canarias 2023](https://github.com/pythoncanarias/pycones23/assets/177982/470d30a4-4c1f-452d-ac35-51e60d85184d)

Ahí están ¿a qué te refieres?

**Comment by sdelquin** [comment]
Buf. Qué raro. El otro día cuando entré no se veían. Nada, olvídalo. Cierro incidencia.
