### ISSUE TITLE
Botón de desplazamiento (landing)

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/pycones23#7]
¿Sería muy difícil que al pulsar esta flecha la página se desplazara al final? 🤔 

![Captura de pantalla 2023-02-21 a las 19 46 55](https://user-images.githubusercontent.com/1591599/220443671-a19553ef-307b-47b2-b313-c856bcc98397.png)

**Comment by cmaureir** [comment]
Si se le agrega un `id` a una sección de abajo, se podría dar la funcionalidad que solo visite `es.pycon.org/#el_id` con ese botón para que se mueva. ¿Sería suficiente?

**Comment by sdelquin** [comment]
Yo creo que es suficiente
